- name: Test Linux connectivity
  hosts: webservers
  become: yes
  tasks:
    - name: Ping
      ansible.builtin.ping:
- name: Test Linux connectivity
  hosts: webservers
  become: yes
  tasks:
    - name: Ping
      ansible.builtin.ping:
