- name: Копируем сертификаты winvist.ru на удалённые сервера
  hosts: all
  become: yes
  tasks:
    - name: Копируем папку winvist.ru целиком
      ansible.builtin.synchronize:
        src: /etc/nginx/ssl/winvist.ru/
        dest: /etc/nginx/ssl/winvist.ru/
        recursive: yes
        rsync_opts:
          - "--chmod=F0600,D0700"
