- name: Создаём общего пользователя + настраиваем SSH
  hosts: all
  become: true

  pre_tasks:
    - name: Создаём пользователя (если ещё нет) и даём sudo без пароля
      user:
        name: "{{ ssh_user }}"
        shell: /bin/bash
        groups: sudo # уберите, если sudo не нужен
        append: true
        state: present
      register: new_user

    - name: Разрешаем sudo без пароля (разово, если пользователь новый)
      copy:
        dest: "/etc/sudoers.d/{{ ssh_user }}"
        content: "{{ ssh_user }} ALL=(ALL) NOPASSWD:ALL\n"
        mode: "0440"
      when: new_user.changed

  roles:
    - role: devsec.hardening.ssh_hardening
      vars:
        # минимальная «умеренная» жёсткость
        ssh_permit_root_login: "no" # root по SSH отключён
        ssh_server_password_login: false # только ключи
        ssh_client_hardening: false # клиент оставляем без твиков
        ssh_print_motd: false # без лишних баннеров
        ssh_server_ports: ["22"] # при желании меняйте здесь
        # → остальные дефолты роли оставляем как есть

  tasks:
    - name: Создаём ~/.ssh
      file:
        path: "/home/{{ ssh_user }}/.ssh"
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0700"

    - name: Кладём публичные ключи всех клиентов
      authorized_key:
        user: "{{ ssh_user }}"
        state: present
        key: "{{ item }}"
      loop: "{{ ssh_user_pubkeys }}"

  handlers:
    - name: Перезапускаем sshd
      service:
        name: sshd
        state: restarted
